// Compile the guardian with solc, resolving OpenZeppelin from node_modules.
//
//   node contracts/evm/compile.mjs     writes src/tripwire/guardian.artifact.ts
//
// The artifact is committed because the dashboard runs this exact bytecode in
// an in-browser EVM. The test suite recompiles in memory and fails if the
// committed artifact has drifted from the source, so the demo can never be
// running a different contract from the one that was tested.
import solc from 'solc';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../..');
export const ARTIFACT_PATH = join(repo, 'src/tripwire/guardian.artifact.ts');

function findImport(path) {
  const hit = [join(here, 'src', path), join(repo, 'node_modules', path)].find(existsSync);
  return hit ? { contents: readFileSync(hit, 'utf8') } : { error: `not found: ${path}` };
}

export function compileGuardian() {
  const input = {
    language: 'Solidity',
    sources: {
      'TripwireGuardian.sol': { content: readFileSync(join(here, 'src/TripwireGuardian.sol'), 'utf8') },
    },
    settings: {
      optimizer: { enabled: true, runs: 200 },
      evmVersion: 'cancun',
      outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object'] } },
    },
  };
  const out = JSON.parse(solc.compile(JSON.stringify(input), { import: findImport }));
  const all = out.errors ?? [];
  const errors = all.filter((e) => e.severity === 'error');
  // Vendored OpenZeppelin warnings are not ours to fix and should not be read as ours.
  const ours = all.filter((e) => e.severity === 'warning' && !e.sourceLocation?.file?.startsWith('@openzeppelin/'));
  const vendored = all.filter((e) => e.severity === 'warning').length - ours.length;
  if (errors.length) return { errors, ours, vendored };
  const c = out.contracts['TripwireGuardian.sol'].TripwireGuardian;
  return {
    errors,
    ours,
    vendored,
    artifact: { abi: c.abi, bytecode: `0x${c.evm.bytecode.object}` },
    runtimeBytes: c.evm.deployedBytecode.object.length / 2,
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const r = compileGuardian();
  r.ours.forEach((w) => console.log('WARNING:', w.formattedMessage.trim()));
  r.errors.forEach((e) => console.error('ERROR:', e.formattedMessage.trim()));
  if (r.errors.length) process.exit(1);
  // A TS module rather than JSON: the app imports it with no bundler or
  // tsconfig changes, and the ABI stays a plain typed value.
  writeFileSync(
    ARTIFACT_PATH,
    '// Generated by contracts/evm/compile.mjs from contracts/evm/src/TripwireGuardian.sol.\n' +
      '// Do not edit. The test suite fails if this drifts from a fresh compile.\n' +
      "import type { GuardianArtifact } from './guardianVM';\n\n" +
      `const artifact: GuardianArtifact = ${JSON.stringify(r.artifact, null, 2)};\n\nexport default artifact;\n`
  );
  console.log(
    `compiled clean — solc ${solc.version().split('+')[0]}, ` +
      `${r.ours.length} warning(s) in our code, ${r.vendored} in vendored OpenZeppelin`
  );
  console.log(`runtime bytecode: ${r.runtimeBytes} bytes (EIP-170 limit 24576)`);
  console.log(`artifact: ${ARTIFACT_PATH.replace(repo + '/', '')}`);
}
